"""initial schema

Revision ID: 497b4b85e0d7
Revises: 
Create Date: 2026-04-05 22:34:10.346915
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497b4b85e0d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_adapter', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('authors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('secondary_domains', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('summary_l1', sa.Text(), nullable=True),
    sa.Column('summary_l2', sa.Text(), nullable=True),
    sa.Column('summary_l3', sa.Text(), nullable=True),
    sa.Column('merged_source_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_articles_canonical_url'), 'articles', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_articles_domain'), 'articles', ['domain'], unique=False)
    op.create_index('ix_articles_domain_published', 'articles', ['domain', 'published_at'], unique=False)
    op.create_table('source_health_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_logs_source_name'), 'source_health_logs', ['source_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('global_depth_fallback', sa.String(length=5), nullable=False),
    sa.Column('exploration_rate', sa.Float(), nullable=False),
    sa.Column('delivery_frequency', sa.String(length=20), nullable=False),
    sa.Column('delivery_time', sa.String(length=10), nullable=False),
    sa.Column('delivery_timezone', sa.String(length=50), nullable=False),
    sa.Column('delivery_channel', sa.String(length=10), nullable=False),
    sa.Column('seed_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('trusted_sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('blocked_domains', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('digests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digests_user_id'), 'digests', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_user_created', 'feedback', ['user_id', 'created_at'], unique=False)
    op.create_table('user_domain_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('depth_preference', sa.String(length=5), nullable=False),
    sa.Column('is_explicit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_domain_preferences_user_id'), 'user_domain_preferences', ['user_id'], unique=False)
    op.create_table('digest_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('digest_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rendered_depth', sa.String(length=5), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('is_exploration', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_items_digest_id'), 'digest_items', ['digest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digest_items_digest_id'), table_name='digest_items')
    op.drop_table('digest_items')
    op.drop_index(op.f('ix_user_domain_preferences_user_id'), table_name='user_domain_preferences')
    op.drop_table('user_domain_preferences')
    op.drop_index('ix_feedback_user_created', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_digests_user_id'), table_name='digests')
    op.drop_table('digests')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_health_logs_source_name'), table_name='source_health_logs')
    op.drop_table('source_health_logs')
    op.drop_index('ix_articles_domain_published', table_name='articles')
    op.drop_index(op.f('ix_articles_domain'), table_name='articles')
    op.drop_index(op.f('ix_articles_canonical_url'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
