"""EmailRenderer — builds Gmail-compatible inline-style HTML for the daily digest."""

from datetime import date
from urllib.parse import quote


_DOMAIN_LABELS = {
    "ai_ml": "AI / ML",
    "tech": "Technology",
    "econ": "Economics",
    "politics": "Politics",
    "biotech": "Biotech",
    "science": "Science",
    "sustainability": "Sustainability",
    "oss": "Open Source",
    "finance": "Finance",
    "crypto": "Crypto",
    "health": "Health",
    "sports": "Sports",
    "entertainment": "Entertainment",
    "education": "Education",
    "startups": "Startups",
    "cybersecurity": "Cybersecurity",
}


class EmailRenderer:
    """Renders a list of article dicts into (subject, html, text) for Resend delivery.

    Constraints:
    - HTML uses inline styles only (Gmail strips <style> blocks).
    - No external images or fonts — email is self-contained.

    Args:
        worker_url: If set, article links are wrapped through the Cloudflare
                    Worker redirect endpoint so mobile clicks are tracked.
    """

    def __init__(self, *, worker_url: str = "") -> None:
        self._worker_url = worker_url.rstrip("/")

    def render(
        self,
        items: list[dict],
        *,
        sent_date: date,
    ) -> tuple[str, str, str]:
        """Return (subject, html_body, text_body)."""
        date_str = sent_date.strftime("%b %-d, %Y")
        subject = f"Your News Digest — {date_str}"
        html = self._render_html(items, date_str)
        text = self._render_text(items, date_str)
        return subject, html, text

    # ------------------------------------------------------------------
    # HTML (inline styles, Gmail-safe)
    # ------------------------------------------------------------------

    def _render_html(self, items: list[dict], date_str: str) -> str:
        cards = "".join(self._article_card(item) for item in items)
        if not cards:
            cards = (
                '<p style="font-family:Arial,sans-serif;font-size:14px;color:#666;">'
                "No articles in today's digest."
                "</p>"
            )

        return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr>
          <td style="background:#111;padding:24px 32px;border-radius:4px 4px 0 0;">
            <p style="margin:0;font-family:Georgia,serif;font-size:22px;font-weight:bold;color:#fff;letter-spacing:-0.02em;">
              Discovery
            </p>
            <p style="margin:4px 0 0;font-family:Arial,sans-serif;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:0.08em;">
              Daily Digest &bull; {date_str}
            </p>
          </td>
        </tr>

        <!-- Articles -->
        <tr>
          <td style="background:#fff;padding:8px 0;">
            {cards}
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f4f4f4;padding:20px 32px;border-top:1px solid #e0e0e0;">
            <p style="margin:0;font-family:Arial,sans-serif;font-size:11px;color:#aaa;text-align:center;">
              Generated by News Agent Collector &bull; Running on your local machine
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>"""

    def _track_url(self, article_id: str, source_url: str) -> str:
        """Return a Worker redirect URL if configured, else the original URL."""
        if not self._worker_url or not article_id:
            return source_url
        encoded = quote(source_url, safe="")
        return f"{self._worker_url}/click/{article_id}?url={encoded}"

    def _article_card(self, item: dict) -> str:
        title = self._escape(item.get("title", "Untitled"))
        summary = self._escape(item.get("summary", ""))
        raw_url = item.get("source_url", "#")
        article_id = item.get("article_id", "")
        url = self._track_url(article_id, raw_url)
        domain_key = item.get("domain", "")
        domain_label = _DOMAIN_LABELS.get(domain_key, domain_key.replace("_", " ").title())
        published = self._escape(item.get("published_at", ""))

        return f"""
        <table width="100%" cellpadding="0" cellspacing="0"
               style="border-bottom:1px solid #f0f0f0;">
          <tr>
            <td style="padding:20px 32px;">
              <p style="margin:0 0 6px;font-family:Arial,sans-serif;font-size:10px;
                        font-weight:bold;text-transform:uppercase;letter-spacing:0.1em;color:#e44;">
                {domain_label}{" &bull; " + published if published else ""}
              </p>
              <h2 style="margin:0 0 8px;font-family:Georgia,serif;font-size:18px;
                         font-weight:bold;color:#111;line-height:1.3;">
                <a href="{url}" style="color:#111;text-decoration:none;">{title}</a>
              </h2>
              <p style="margin:0 0 12px;font-family:Arial,sans-serif;font-size:14px;
                        color:#444;line-height:1.6;">
                {summary}
              </p>
              <a href="{url}" style="font-family:Arial,sans-serif;font-size:12px;
                                    font-weight:bold;color:#e44;text-decoration:none;
                                    text-transform:uppercase;letter-spacing:0.06em;">
                Read &rarr;
              </a>
            </td>
          </tr>
        </table>"""

    # ------------------------------------------------------------------
    # Plain text fallback
    # ------------------------------------------------------------------

    def _render_text(self, items: list[dict], date_str: str) -> str:
        lines = [f"Discovery — Daily Digest — {date_str}", "=" * 50, ""]
        for item in items:
            lines.append(item.get("title", "Untitled"))
            summary = item.get("summary", "")
            if summary:
                lines.append(summary)
            lines.append(item.get("source_url", ""))
            lines.append("")
        if not items:
            lines.append("No articles in today's digest.")
        return "\n".join(lines)

    @staticmethod
    def _escape(text: str) -> str:
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
